### PR TITLE
MultiOS makefile + build/burn instruction on Linux

### PR DESCRIPTION
**Pull request by luipir**
Makefile.multiOS and instruction build and burn on linux (probably working on OSX too)

### CODE REVIEW

**Comment by luipir** [comment]
@dalathegreat just a first draft... updated my OS and I've to reinstall some libs to be sure that the makefile works correctly.
e.g. do not merge yet

**Comment by luipir** [comment]
@dalathegreat makefile for linux is in working state now, able to merge

**Comment by glynhudson** [comment]
Nice work @luipir! I've just tried to test compiling on Linux. 

There wasn't any mention of the required packages in the installation docs, however I figured the following would be needed:

`sudo apt-get install gcc-avr binutils-avr avr-libc`

I keep getting error:

```
$ make -f Makefile.multiOS all
Descriptors.d:1: *** multiple target patterns. Stop.
```
Any idea what I'm missing? 





I'm testing on Ubuntu 20.04

**Comment by luipir** [comment]
@glynhudson I'll check tomorrow on the laptop where I've the setup

**Comment by luipir** [comment]
> ```
> $ make -f Makefile.multiOS all
> Descriptors.d:1: *** multiple target patterns. Stop.
> ```
@glynhudson did you edit something inside the makefile? this error happen when Makefile find multiple targets (separated by ":") when expect only one.
Could be I did a wrong commit, I'll check if a clean clone give the error. BTW please check if you did some syntax error editing Makefile

**Comment by luipir** [comment]
@glynhudson confirmed the issue on my laptop with a clean clone of the repo... giving a look

**Comment by luipir** [comment]
@glynhudson the issue is that, now this line:
https://github.com/dalathegreat/Nissan-LEAF-CCS/blob/main/leaf-can-bridge-3-port-CCS/Debug/Makefile.multiOS#L22
is returning True => inject some not escaped ":"

Investigating a workaround

**Comment by luipir** [comment]
right... this is the problem and this is the workaround
The repo contains precompiled (under win) Descriptors.d files. For some magic, Makefile is able to infer OS basing on this (probably for cross compilation) => assume that OS is win that the issue.

the workaround is:
`$> make -f Makefile.multiOS clean` that can give some error like "cmd.exe" not found for the reason above, but rm is applied to the most of files => you can then compile as usual.

I'll do a PR in the INSTALL.md to document this issue.

**Comment by luipir** [comment]
Hi @glynhudson and @dalathegreat updated build documentation (not in the wiki) to avoid the issue raised by @glynhudson 
https://github.com/dalathegreat/Nissan-LEAF-CCS/pull/3

**Pull request merged**
