### PR TITLE
updated guide to compile under LInux to avoid issue due the presence of win precompiled files

### PR DESCRIPTION
**Pull request by luipir**
This would fix issue commented here:
https://github.com/dalathegreat/Nissan-LEAF-CCS/pull/2#issuecomment-1045546493

### CODE REVIEW

**Comment by luipir** [comment]
FYI @glynhudson plese check the new documentation and comment here if it works.
To @dalathegreat wait for glyn verification before to approve and merge

**Comment by glynhudson** [comment]
Nice work! This worked for me, it now compiles successfully on Linux :-) 

Thanks a lot for taking the time to investigate this.

**Comment by luipir** [comment]
> Thanks a lot for taking the time to investigate this.

"to great code contribution great responsibilities" (cit. the uncle of Ken Parker) ;)

**Comment by luipir** [comment]
btw  @glynhudson  what is your linux setup on can bus sniffing.... I'm having many issues with many devices.

**Comment by glynhudson** [comment]
I use OVMS https://docs.openvehicles.com/en/latest/crtd/can_logging.html

**Comment by dalathegreat** [comment]
Awesome work you two! 👍

**Pull request merged**
